"""Event service — CRUD operations and business logic for events."""

import logging
from datetime import datetime, timedelta, timezone
from typing import Optional

from sqlalchemy import and_, case, func
from sqlalchemy.orm import Session, selectinload

from app.models import Event, Ticket
from app.schemas import SeverityBreakdown, TimelinePoint

logger = logging.getLogger(__name__)

# Severities that trigger an emergency call
_CALL_SEVERITIES = {"high", "medium"}


def create_event(
    db: Session,
    event_type: str,
    confidence: float,
    severity: str,
    evidence_path: Optional[str] = None,
    bbox_data: Optional[list[dict]] = None,
    source_video: Optional[str] = None,
    frame_number: Optional[int] = None,
    metadata: Optional[dict] = None,
    source: str = "manual",  # "manual" (upload) | "cctv" (live monitor)
    commit: bool = True,
    dispatch_notifications: bool = True,
) -> Event:
    """Create a new event in the database.

    Args:
        source: Origin of the detection — ``"manual"`` for uploaded files,
            ``"cctv"`` for events generated by live camera monitors.
            Used to select the appropriate ``TWILIO_ENABLED_*`` flag.
    """
    event = Event(
        event_type=event_type,
        confidence=confidence,
        severity=severity,
        evidence_path=evidence_path,
        bbox_data=bbox_data,
        source_video=source_video,
        frame_number=frame_number,
        metadata_=metadata,
    )
    db.add(event)
    db.flush()

    if commit:
        db.commit()
        db.refresh(event)

    logger.info("Created event: %s", event)

    if dispatch_notifications:
        dispatch_event_notifications(db, event, source=source)

    return event


def _build_alert_details(event: Event, source: str = "manual") -> dict:
    metadata = event.metadata_ or {}
    return {
        "event_id": event.id,
        "event_type": event.event_type,
        "severity": event.severity,
        "confidence": event.confidence,
        "timestamp": event.timestamp.isoformat(),
        "bbox_data": event.bbox_data,
        "evidence_path": event.evidence_path,
        "source_video": event.source_video,
        "source": source,
        "camera_id": metadata.get("camera_id"),
        "camera_name": metadata.get("camera_name", ""),
        "camera_stream_url": metadata.get("camera_stream_url", ""),
        "camera_snapshot_url": metadata.get("camera_snapshot_url", ""),
        "camera_lat": metadata.get("camera_lat"),
        "camera_lng": metadata.get("camera_lng"),
    }


def dispatch_event_notifications(db: Session, event: Event, source: str = "manual") -> None:
    """Dispatch configured notifications for an event if it is alert-worthy."""
    if event.event_type != "accident" or event.severity not in _CALL_SEVERITIES:
        return

    from app.services.notification_service import dispatch_alerts  # lazy import

    dispatch_alerts(_build_alert_details(event, source=source), db)


def list_events(
    db: Session,
    event_type: Optional[str] = None,
    severity: Optional[str] = None,
    ticket_status: Optional[str] = None,
    limit: int = 50,
    offset: int = 0,
    date_from: Optional[datetime] = None,
    date_to: Optional[datetime] = None,
    include_tickets: bool = False,
) -> tuple[list[Event], int]:
    """List events with optional filtering. Returns (events, total_count)."""
    query = db.query(Event)

    if include_tickets:
        query = query.options(selectinload(Event.tickets))

    if event_type:
        query = query.filter(Event.event_type == event_type)
    if severity:
        query = query.filter(Event.severity == severity)
    if ticket_status:
        query = query.join(Ticket, Ticket.event_id == Event.id).filter(Ticket.status == ticket_status)
        query = query.distinct()
    if date_from:
        query = query.filter(Event.timestamp >= date_from)
    if date_to:
        query = query.filter(Event.timestamp <= date_to)

    id_query = query.order_by(None).with_entities(Event.id)
    total = db.query(func.count()).select_from(id_query.subquery()).scalar() or 0
    events = query.order_by(Event.timestamp.desc()).offset(offset).limit(limit).all()
    return events, total


def get_event(db: Session, event_id: str) -> Optional[Event]:
    """Get a single event by ID."""
    return db.query(Event).filter(Event.id == event_id).first()


def get_stats(db: Session) -> dict:
    """Get aggregate statistics for the dashboard."""
    totals = db.query(
        func.count(Event.id).label("total_events"),
        func.sum(case((Event.event_type == "accident", 1), else_=0)).label("total_accidents"),
        func.sum(case((and_(Event.event_type == "accident", Event.severity == "high"), 1), else_=0)).label("severity_high"),
        func.sum(case((and_(Event.event_type == "accident", Event.severity == "medium"), 1), else_=0)).label("severity_medium"),
        func.sum(case((and_(Event.event_type == "accident", Event.severity == "low"), 1), else_=0)).label("severity_low"),
    ).one()

    total_events = int(totals.total_events or 0)
    total_accidents = int(totals.total_accidents or 0)
    severity_high = int(totals.severity_high or 0)
    severity_medium = int(totals.severity_medium or 0)
    severity_low = int(totals.severity_low or 0)

    # 24h timeline (single grouped query)
    now = datetime.now(timezone.utc)
    window_start = now - timedelta(hours=23)
    timeline_counts: dict[str, int] = {}

    dialect_name = ""
    if db.bind is not None and db.bind.dialect is not None:
        dialect_name = db.bind.dialect.name

    if dialect_name == "postgresql":
        hour_bucket = func.date_trunc("hour", Event.timestamp)
        rows = (
            db.query(hour_bucket.label("hour_bucket"), func.count(Event.id))
            .filter(Event.timestamp >= window_start)
            .group_by(hour_bucket)
            .all()
        )
        for bucket, count in rows:
            timeline_counts[bucket.strftime("%H:00")] = int(count or 0)
    else:
        # SQLite / fallback path for test environments.
        hour_bucket = func.strftime("%Y-%m-%d %H:00", Event.timestamp)
        rows = (
            db.query(hour_bucket.label("hour_bucket"), func.count(Event.id))
            .filter(Event.timestamp >= window_start)
            .group_by(hour_bucket)
            .all()
        )
        for bucket, count in rows:
            if bucket:
                timeline_counts[str(bucket)[11:16] + ":00"] = int(count or 0)

    timeline: list[TimelinePoint] = []
    for i in range(24):
        hour_start = window_start + timedelta(hours=i)
        label = hour_start.strftime("%H:00")
        timeline.append(TimelinePoint(
            hour=label,
            count=timeline_counts.get(label, 0),
        ))

    return {
        "total_events": total_events,
        "total_accidents": total_accidents,
        "severity_breakdown": SeverityBreakdown(
            high=severity_high, medium=severity_medium, low=severity_low
        ),
        "timeline_24h": timeline,
    }
